name: passport_visa_api
description: A sample command-line application.
version: 1.1.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  json_serializable: ^6.6.2
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  dio: ^5.1.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  equatable: ^2.0.5
