name: Build Develop
on:
  push:
    branches:
      - develop
    pull_request:
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.3]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    # container: 'golang:1.16.3'
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: echo "Hello World!"
