name: Test
on:
  push:
    branches:
      - develop
    pull_request:
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.3]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    # container: 'golang:1.16.3'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test version
        run: cd pkg/version && go test -v && ../../
      - name: Test memory
        run: cd pkg/storage/memory && go test -v && ../../../
